### ISSUE TITLE
[Suggestion] Change mod download source

### ISSUE THREAD

**Issue by viiuan** [Tre5et/treelauncher#7]
(Unless I am missing something) it would be nice to be able to choose which mod source to download from, as it seems at the whim of the launcher itself whether I get the mod from Curseforge or Modrinth.

**Comment by Tre5et** [comment]
In version 2.4.0 you can now prioritize or outright disable mod sources (Modrinth and Curseforge). The launcher will then download any new mod versions from the highest prioritized source.

Previously, versions would have always been downloaded from Modrinth if available, otherwise from Curseforge. This is still the default behavior.

If a mod isn't downloaded from the platform you intended (indicated by that platform's logo being colored in the comfortable list display), make sure that the launcher has correctly found the mod on both platforms (indicated by the other platform's logo being bright rather than dark gray). Otherwise, try to remove the mod and re-search for it. There was previously an issue that would make search results from Curseforge pretty bad. If this doesn't help, you can add a platform as a source to an installed mod manually.
